<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.0.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>d5c73682-3234-4d99-a654-9519f05393ca</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SignalR Demo.ApiService\SignalR Demo.ApiService.csproj" />
    <ProjectReference Include="..\SignalR Demo.Web\SignalR Demo.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.0.0" />
  </ItemGroup>

</Project>
